# Generated by Django 6.0.3 on 2026-04-09 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_organisateur'),
        ('locations', '0002_remove_location_capacite'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lieu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
    ]
