# Generated by Django 6.0.3 on 2026-03-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('capacite_max', models.IntegerField()),
            ],
        ),
    ]
