# Generated by Django 6.0.3 on 2026-04-09 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='present',
        ),
        migrations.AddField(
            model_name='participation',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
